#!/bin/bash
# script that relies on pmtoggle to create a file in /tmp
# then activates system76-power to change profiles in response to changes in AC supply.
sleep 1 #wait a bit after suspend

# change USERNAME if needed manually. This attempts to automatically determine your username
USERNAME=$(who | grep "\(${_display_id}\)" | awk '{print $1}' | head -n 1)

# Functions:
function checker() {
    ## If the tmp file has value 0, that means that there is no AC attached
    if [ ! -z "$(tail -n2 /tmp/pmtoggle | grep '0')" ]; then
        echo "1" | sudo tee /sys/devices/system/cpu/intel_pstate/no_turbo #turn off turbo boost
        echo "AC not attached. Disabling turbo boost mode..."

    ## Else, if the tmp file has value 1, that means there is AC attached
    else
        echo "0" | sudo tee /sys/devices/system/cpu/intel_pstate/no_turbo #turn on turbo boost
        echo "AC attached. Enabling turbo boost mode..."
    fi
}

# toggler() is what changes the power profiles. It additionally can take other args to execute
# Polling is expensive. Let us use inotify.
function toggler() {
    checker #run first in case the /tmp file has not been modified yet
    inotifywait --monitor --format "%e %w%f" --event modify,create /tmp/pmtoggle | while read changed; do
        checker
    done
}

# If this be first boot, run pmtoggle manually
pmtoggle
toggler
