#!/bin/bash

# power profile commands
# set these up to match your power profile backend (power-profiles, tuned, etc)
# they don't have to be all different! For example, you can set all three to powersave if you want.
PERFORMANCE="tuned-adm profile balanced"
BALANCED="tuned-adm profile balanced"
POWER="tuned-adm profile powersave-powertop"

# cpu threshold at which to activate turbo boost
TURBO_CPU_THRESHOLD="55"

# at what change in load values should the power governer automatically switch to PERFORMANCE
# load deltas are just difference in load values between 4 seconds. For example, 1.82 - 1.20 = 0.62
LOAD_DELTA_THRESHOLD="0.35"

# limits at which to switch to a more powerful or weaker power governor
# generally, you can treat LOWER_CPU_THRESHOLD as the point between POWER and BALANCED
# HIGHER_CPU_LIMIT is the point between BALANCED and PERFORMANCE
# For example, if you have a cpu usage greater than LOWER_CPU_THRESHOLD but lower than HIGHER_CPU_THRESHOLD,
# you will most likely have the BALANCED profile set.
LOWER_CPU_THRESHOLD="35"
HIGHER_CPU_THRESHOLD="65"

# prints out the load delta and cpu usage as debugs to logs. The format as follows:
# LOAD DELTA: -4, CPU: 3, NO_TURBO: 1
# Load deltas are reported in HUNDREDTHS! (15 = 0.15 difference)
# No_turbo values are 1 (turbo off), and 0 (turbo on)
# no matter this setting, you will see messages of the switches between power profiles
# Set DEBUG_LOG to 1 to enable it, any other value to disable it
DEBUG_LOG=0 #default disabled

######################################################################
## DO NOT MODIFY BELOW THIS LINE UNLESS YOU KNOW WHAT YOU ARE DOING ##
######################################################################

# Script to automatically change power management settings based on system usage.
rm /tmp/dynamic-profiler

#precheck tmp file
if ! [ -f /tmp/dynamic-profiler ]; then #create a tmp file
  echo "No tmp file found. Creating as /tmp/dynamic-profiler"
  touch /tmp/dynamic-profiler > /dev/null
fi

#define functions
check_tmp () {
  if [[ $(cat /tmp/dynamic-profiler) == "$1" ]]; then
    return 1
  fi
}

turbo_set () {
  cpu_check="$(echo "$1 > $TURBO_CPU_THRESHOLD" | bc -l)"
  turbo=$(cat /sys/devices/system/cpu/intel_pstate/no_turbo)
  if [ $cpu_check -eq 1 ]; then
    if [ $turbo == "1" ]; then
      echo "0" | sudo tee /sys/devices/system/cpu/intel_pstate/no_turbo > /dev/null #turn on boost
    fi
  else
    if [ $turbo == "0" ]; then
      echo "1" | sudo tee /sys/devices/system/cpu/intel_pstate/no_turbo > /dev/null #turn off boost
    fi
  fi
  turbo=$(cat /sys/devices/system/cpu/intel_pstate/no_turbo) #redefine it for debugger
}

performance_set () {
  check_tmp "performance"
  check_ret=$?
  if [[ $check_ret != 1 ]]; then
    $PERFORMANCE
    echo "Performance Mode set!"
    echo "performance" | tee /tmp/dynamic-profiler > /dev/null
  fi
}

balanced_set () {
  check_tmp "balanced"
  check_ret=$?
  if [[ $check_ret != 1 ]]; then
    $BALANCED
    echo "Balanced Mode set!"
    echo "balanced" | tee /tmp/dynamic-profiler > /dev/null
  fi
}

power_set () {
  check_tmp "power"
  check_ret=$?
  if [[ $check_ret != 1 ]]; then
    $POWER
    echo "Power Mode set!"
    echo "power" | tee /tmp/dynamic-profiler > /dev/null
  fi
}

debug_log () {
  if [[ $DEBUG_LOG == 1 ]]; then
    echo "LOAD DELTA: $int_load_diff, CPU: $cpu, NO_TURBO: $turbo"
  fi
}

## Main loop
while true
do
  if [ -f /tmp/dynamic-profiler-lock ]; then
    echo "" | tee /tmp/dynamic-profiler > /dev/null
    if [ -f /tmp/dynamic-profiler-turbo-on ]; then
      echo "0" | sudo tee /sys/devices/system/cpu/intel_pstate/no_turbo > /dev/null 
      echo "Turbo Mode enabled manually"
      rm /tmp/dynamic-profiler-turbo-on
    elif [ -f /tmp/dynamic-profiler-turbo-off ]; then
      echo "1" | sudo tee /sys/devices/system/cpu/intel_pstate/no_turbo > /dev/null
      echo "Turbo Mode disabled manually"
      rm /tmp/dynamic-profiler-turbo-off
    fi
    if [ -f /tmp/dynamic-profiler-manual ]; then
      man_sett=$(cat /tmp/dynamic-profiler-manual)
      if [[ $man_sett == "performance" ]]; then
          $PERFORMANCE
          echo "Performance Mode set manually"
      elif [[ $man_sett == "balanced" ]]; then
          $BALANCED
          echo "Balanced Mode set manually"
      elif [[ $man_sett == "power" ]]; then
          $POWER
          echo "Power Mode set manually"
      fi
      rm /tmp/dynamic-profiler-manual
    fi
    sleep 4
  else
    #Get CPU info
    top_get="$(top -bn1 | grep -o -e 'load average.*' -e 'Cpu(s).*')"
    cpu="$(echo "$top_get" | tail -n 1 | awk '{ print $2 '+' $4; }' | bc)"
    int_cpu=$(printf "%.*f\n" 0 $cpu) #simplify calculations later on

    #Get Load difference info
    load_1="$(echo $(uptime) | grep -o -e 'load average.*' | awk '{print $3;}' | tr ',' ' ')"
    sleep 4 #gather data
    load_2="$(echo $(uptime) | grep -o -e 'load average.*' | awk '{print $3;}' | tr ',' ' ')"
    load_diff="$(echo $load_2 - $load_1 | bc)"
    load_diff_100=$(echo "$load_diff*100" | bc) #its easier to get an int for bash calculations
    int_load_diff=$(printf "%.*f\n" 0 $load_diff_100) #conversion to int
    load_delta_100=$(echo "$LOAD_DELTA_THRESHOLD*100" | bc) #make sure scale is the same
    int_load_delta=$(printf "%.*f\n" 0 $load_delta_100) #conversion to in

    if [[ $int_load_diff -lt 0 ]] && [[ $int_cpu -lt $LOWER_CPU_THRESHOLD ]]; then
      power_set
    elif [[ $int_load_diff -lt 0 ]] && [[ $int_cpu -ge $HIGHER_CPU_THRESHOLD ]]; then
      balanced_set
    elif [[ $int_load_diff -ge $int_load_delta ]]; then #like an AP depolarization
      performance_set
    elif [[ $int_load_diff -gt 0 ]] && [[ $int_cpu -ge $HIGHER_CPU_THRESHOLD ]]; then
      performance_set
    elif [[ $int_load_diff -gt 0 ]] && [[ $int_cpu -gt $LOWER_CPU_THRESHOLD ]]; then
      balanced_set
    #else
      #echo "edge case, nothing done" #this really is an edge case, but it allows us to keep previous settings
    fi
    turbo_set $int_cpu
    debug_log
  fi
done

