#!/bin/bash
# script that relies on pmtoggle to create a file in /tmp
# then activates system76-power to change profiles in response to changes in AC supply.

# change USERNAME if needed manually. This attempts to automatically determine your username
USERNAME=$(who | grep "\(${_display_id}\)" | awk '{print $1}' | head -n 1)

# Functions:
# Following function adapted from https://stackoverflow.com/questions/20292578/setting-gsettings-of-other-user-with-sudo
function runas() {
    display_id=":$(find /tmp/.X11-unix/* | sed 's#/tmp/.X11-unix/X##' | head -n 1)"
    user_id=$(id -u "$USERNAME")
    environment=("DISPLAY=$display_id" "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$user_id/bus")
    sudo -Hu "$USERNAME" env "${environment[@]}" "$@" #we do this to execute functions such as notify-send or gsettings
}

# toggler() is what changes the power profiles. It additionally can take other args to execute
# Polling is expensive. Let us use inotify.
function toggler() {
    inotifywait --monitor --format "%e %w%f" --event modify,create /tmp/pmtoggle | while read changed; do
        ## If the tmp file has value 0, that means that there is no AC attached
        if [ ! -z "$(tail -n2 /tmp/pmtoggle | grep '0')" ]; then
            system76-power profile battery
            $1
            runas notify-send "Power Management" "AC disconnected. Entering power-saving mode."
            echo "AC not attached. Entering powersave mode..."

        ## Else, if the tmp file has value 1, that means there is AC attached
        else
            system76-power profile performance
            $2
            runas notify-send "Power Management" "AC connected. Entering performance mode."
            echo "AC attached. Entering performance mode..."
        fi
    done
}

# If this be first boot, run pmtoggle manually
pmtoggle
if ! [[ -z "$(ls /usr/bin/*-session | grep gnome)" ]]; then #check if we are on gnome
  echo "Running on gnome..." #if yes, run toggler with additional gsettings args to toggle animations
  toggler "runas gsettings set org.gnome.desktop.interface enable-animations false" "runas gsettings set org.gnome.desktop.interface enable-animations true"
else
  echo "Not running on gnome..." #if not on gnome, run toggler normally
  toggler
fi
