#!/bin/bash
# Script to toggle turbo boost for intel cpus.
# Additionally toggles animations on GNOME
USERNAME=

# First define a function that can take in extra parameters if needed
function toggler() {
  if [ $turbo == "0" ]; then #boost on
    echo "Boost is On. Turning off..."
    $1
    echo "1" | sudo tee /sys/devices/system/cpu/intel_pstate/no_turbo #turn on turbo boost
  else #boost off
    echo "Boost is Off. Turning on..."
    $2
    echo "0" | sudo tee /sys/devices/system/cpu/intel_pstate/no_turbo #turn off turbo boost
  fi
}

#Then, check if running on GNOME, and act accordingly
turbo=$(cat /sys/devices/system/cpu/intel_pstate/no_turbo)
if ! [[ -z "$(ls /usr/bin/*-session | grep gnome)" ]]; then
  echo "Running on gnome..."
  ## Following function adapted from https://stackoverflow.com/questions/20292578/setting-gsettings-of-other-user-with-sudo
  function runas() {
      display_id=":$(find /tmp/.X11-unix/* | sed 's#/tmp/.X11-unix/X##' | head -n 1)"
      user_id=$(id -u "$USERNAME")
      environment=("DISPLAY=$display_id" "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$user_id/bus")
      sudo -Hu "$USERNAME" env "${environment[@]}" "$@"
  }
  toggler "runas gsettings set org.gnome.desktop.interface enable-animations false" "runas gsettings set org.gnome.desktop.interface enable-animations true"
else
  echo "Not running on gnome..."
  toggler
fi
