#!/usr/bin/bash
# Script to toggle trackpad/touchpad on or off
state=$(gsettings get org.gnome.desktop.peripherals.touchpad send-events)
if [ $state == "'enabled'" ]; then
	gsettings set org.gnome.desktop.peripherals.touchpad send-events disabled
	notify-send touchpadtoggle "Touchpad Disabled"
elif [ $state == "'disabled'" ]; then
	gsettings set org.gnome.desktop.peripherals.touchpad send-events enabled
	notify-send touchpadtoggle "Touchpad Enabled"
else
    echo "Something went wrong"
fi
