#!/bin/bash
#script to determine whether AC is attached, and if so, trigger system76-power >
AC=$(acpi -V | grep "off-line")

sleep 5

if [ ! -z "$AC" ];then
    system76-power profile battery
else
    system76-power profile performance
fi
